version: 2.0

defaults: &defaults

  working_directory: /home/circleci/signal-cli

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

references:
  java_env: &java_env
    docker:
    - image: circleci/openjdk:8-jdk-browsers-legacy
  container_config: &container_config
    docker:
    - image: docker:18.05.0-ce-git

  dockerhub_login: &dockerhub_login
    run:
      name: DockerHub Login
      command: |
        docker login -u ${DOCKERHUB_LOGIN} -p ${DOCKERHUB_PASS}

jobs:
  compile_artefact:
    <<: *defaults
    <<: *java_env

    steps:
    - *attach_workspace
    - checkout
    - run:
        name: Execute Gradle
        no_output_timeout: 20m
        command: |
          ./gradlew build
    - run:
        name: Create shell wrapper in build/install/signal-cli/bin
        command: |
          ./gradlew installDist
    - run:
        name: Create tar file in build/distributions
        command: |
          ./gradlew distTar
    - store_artifacts:
        path: ./build/distributions/signal-cli-0.6.0.tar
    - store_artifacts:
        path: ./build/distributions/signal-cli-0.6.0.zip
    - persist_to_workspace:
        root: *workspace_root
        paths:
        - .

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - compile_artefact
